[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
verbosity = 2
auto_detect_solc = true
via_ir = true
evm_version = "prague"
ignored_warnings_from = ["src/flattened/Office.flattened.sol"]

[profile.deploy]
via_ir = false
optimizer = true
optimizer_runs = 500

[profile.deploy_office]
via_ir = true
optimizer = true
optimizer_runs = 20
ast = true
build_info = true
extra_output = ["storageLayout"]
ffi = true

[profile.create2]
via_ir = false
always_use_create_2_factory = true
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 500

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
sort_imports = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = false
ignore = ["test/**/*", "src/flattened/**/*"]

[lint]
lint_on_build = false

[doc]
out = "docs/forge-docs"
title = "DYTM"
repository = "https://github.com/dhedge/DYTM"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}" }

[soldeer]
remappings_generate = true
recursive_deps = true
remappings_version = false

[dependencies]
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
"@openzeppelin-contracts" = "5.3.0"
solmate = "6.8.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
